### PR TITLE
sln, vcxproj, packages.config generation

### PR DESCRIPTION
**Pull request by pmienk**
Additional in-progress vcxproj.filers work (requires uuid generation and incrementing).

### CODE REVIEW

**Comment by pmienk** [comment]
Intended to address #54

**Comment by evoskuil** [comment]
This is some great work. How close are we to being able to emit builds for multiple (or other) VS versions?

**Comment by pmienk** [comment]
Unknown.  Will require an environment change or reading before I can
provide specifics.  I'd assume vcxproj would be confined to msbuild
version, CTP reference and variation of nuget packages (which shouldn't be
difficult given the introduced registry, just need a differentiator).
Solution file seemed exceedingly simple, so I'd imagine any change would be
too.

-- Phillip

**Comment by pmienk** [comment]
Will reissue when filters generation is confirmed.

**Pull request closed without merging**
