### PR TITLE
Vary compiler version between min and current among travis linux builds.

### PR DESCRIPTION
**Pull request by pmienk**

### CODE REVIEW

**Comment by evoskuil** [comment]
I'd recommend using the missing `version` attribute to indicate "latest". In the interest of brevity and minimization of special values, that's the convention previously used.

**Comment by pmienk** [comment]
Note that both absence or the use of 'latest' achieve the same outcome.

**Comment by evoskuil** [comment]
Another reason to not use it, ambiguity :).

**Comment by pmienk** [comment]
Good point.  I'll verify and pull out the sentinel.  It had been a forcing function to make sure all lines were updated in the xml while developing.

**Comment by pmienk** [comment]
See #111

**Pull request merged**
